### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by deathbeam** [EclipseEngine/Eclipse-Origins#1]
Hey guys, you do not have any license in repository, so this makes EO unusable.

**Comment by Xender** [comment]
@deathbeam - No, in most legal systems, no license means "all rights reserved", definitely not "public domain".

So as it is, anyone can look at the sources, or AFAIK click the "fork" button to make copy (this is only because it's mentioned in Github's ToS that anyone publishing a repo allows to fork it), but you cannot use it nor make any changes.

**Comment by ghost** [comment]
You can't modify the license or take ownership of the source.

**Comment by Xender** [comment]
@Aeirex - exactly. [The part about forking in GH ToS](https://help.github.com/articles/github-terms-of-service/#f-copyright-and-content-ownership) is IMO just for that no one gets sued for clicking the "Fork" button on the site. Otherwise, no license means that AFAIK (IANAL) for ordinary viewer, only Fair Use rights are in place, which are very limited.

**Comment by deathbeam** [comment]
So as you said @Xender, this means that noone can actually use EO to make game without license. That is even worse that I thought it was. Anyway, atleast people will stop using VB6.

**Comment by ghost** [comment]
@deathbeam, you can make a game without licensing the engine. You compile the engine, the binaries are a state of closed. The thing you can't do is change the license, such as the IP belongs to Eclipse Origins. The game itself, is your own property when it is actually compiled.

**Comment by Xender** [comment]
@Aeirex - Sorry, but I have to disagree with you.
I am not aware of any implied right to use an engine/framework/library in case when sources or binaries+headers are published, but a license is not explicitly granted.

First of all, without a right to redistribute engine binaries (either compiled by yourself of by the upstream; that doesn't matter) distributing your game using the engine would be trickier than common sense tells it should be, that is it would require the end user to download the engine from the officially published repository.
That being said, this sometimes happens - Audacity on Windows requires (or used to require) the user to individually download LAME library in order to export files in mp3 format. On systems with a package manager like GNU/Linux it becomes the distro maintainers' problem instead.
The point is that such situations usually indicate a legal pathology of some sort - in case of LAME it's patent problems.

Second matter is that whether the engine API itself is copyrightable or not.
If it can be considered copyrightable, then even the distribution model of "users have to download the engine by themselves" could be legally unclear.
In this case, the Fair Use rights would allow you to make a game using that API and maybe share it to your friends, but the matter of distributing it publicly would still be unclear.

Also, AFAIK compiling things is a technical matter that is irrelevant as far as copyright law is concerned - unless a license explicitly mentions such technical matters.

See also: https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license

**Comment by ghost** [comment]
Zarachi doesn't care if you make a game with it. He just disallows modifying the license.
